### ISSUE TITLE
Problem with overritten `get_queryset()` method

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#15]
I just found a really annonying thing: If you override the manager and its `get_queryset()` method like this:

```
class MyManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().exclude(
            show_on_website=False)
```

Then scrubber won't scrub the data with `show_on_website=False`.

Any ideas about that topic? Is there a way to avoid the default manager and go directly to the django-base one?

Best regards
Ronny

**Comment by costela** [comment]
And I assume this manager is then set to the `objects` attribute to become the default manager? 

Maybe I'm missing some obvious use-case , but this seems like a strange thing to do. It means you have to jump through hoops everytime you want to access the "full" data. And means some data you might add or change suddenly becomes "invisible" to unknowing users of your model. Sounds a bit like an anti-pattern.

That being said, I believe it should be possible to "reset" the model's manager to `models.Manager()` before accessing it. I'm just not sure it's worth it to try and work around this kind of usage.

**Comment by GitRon** [comment]
I agree about the anti-pattern, the question is if this is easy to implement and low on ressources on runtime. If so, I suggest we do it. It's kind of a bummer if you use scrubber and then end up with some ouf your data still being not anonymised...

**Comment by mastacheata** [comment]
> It's kind of a bummer if you use scrubber and then end up with some ouf your data still being not anonymised...

But isn't that actually what you want? I mean you defined the manager to explicitly exclude the show_on_website field from all queries. To me this sounds like you'd actually want the scrubber to exclude that field as well even if you define a replacement strategy for it.

Also is this really your use case? A simple boolean field? Or is this just for the matter of having an example?
1. A boolean field doesn't have much entropy by itself.
2. Are you sure "Show on Website" is something worth anonymizing? Can people really draw conclusions from that flag or is it only for the sake of it or are you maybe trying to abuse the scrubber for testing purposes?

**Comment by costela** [comment]
@mastacheata your first point is precisely why I'm reluctant to add this. 

As for the second, I think we may have a slight misunderstanding: the *content* of the `show_on_website` field is irrelevant for @GitRon 's argument. It's not even necessarily being scrubbed. It would, however, indirectly cause whole **rows** to not be scrubbed.

**Comment by mastacheata** [comment]
Ahh, yeah, it's late. 🤦‍♂ 
It's not filtering out the show_on_website field, but every record where show_on_website is false, right?
But still that's what the manager is built for, explicitly excluding those very rows, so I feel changing this in django_scrubber would be the wrong place. 🤷‍♂

**Comment by GitRon** [comment]
Hm, I think if there is a simple way (which I don't know about) to take the default manager, it would be the way we'd expect scrubber to work. Maybe we can connect it to a settings var.

But as anonymization is by law very critical I think the default behaviour should be: Kill everything, no matter what.

**Comment by lociii** [comment]
@GitRon overriding ```objects``` on your model defines the default manager. I don't see a reason why scrubber should work around explicitly defined restrictions on your model/queryset.
My approach to your "problem" would be to set a second manager and use e.g. ```MyModel.visible_on_website.all()``` and leave the default ```objects``` as they are intended.

Please don't be mad but I will reject this issue now because mostly everyone agreed it's not how managers should be used and we shouldn't leave such requests open forever.

**Comment by GitRon** [comment]
Hi @lociii 

no worries, I just submit to the majority 😄 

Best 
Ronny
