### ISSUE TITLE
Compat with Faker 3.0.0

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#22]
When using Faker 3.0.0, scrubber throws this error:

> TypeError: Calling `.seed()` on instances is deprecated. Use the class method `Faker.seed()` instead.

**Comment by costela** [comment]
This should already be "fixed" in `0.4.3`. What version are you on?

**Comment by GitRon** [comment]
`0.4.3` 😕

**Comment by costela** [comment]
ah, indeed, "fixed" it only enough for the tests to pass. I'll take a look later.

**Comment by GitRon** [comment]
Cheers 👍

**Comment by costela** [comment]
Please give 0.4.4 a try. It's a stop-gap while I don't get around to actually supporting faker >= 3, but it should at least downgrade gracefully, if you're using something like `pip-tools` or `pipenv`. Pure `pip` will probably just complain about an incompatibility, but install anyway :man_shrugging:

**Comment by GitRon** [comment]
Awesome! Thanks!

**Comment by costela** [comment]
I'll leave this open until I get around to a _proper_ fix :wink:
