### ISSUE TITLE
Using faker geo providers does not work

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#23]
* Django Scrubber version: Latest
* Django version: 2.2.9
* Python version: 3.6
* Operating System: Win10

Hi there!

I tried to scrub lat and long fields with the faker provider but it does not work.

Here's a model:

```
class MyModel(models.Model):
    latitude = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=8)
    longitude = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=8)

    class Scrubbers:     
        latitude = scrubbers.Faker('latitude')
        longitude = scrubbers.Faker('longitude')
```

This will lead to:

> CommandError: DataError while scrubbing <class 'apps.core.models.MyModel'> ((1264, "Out of range value for column '(null)' at row 1"))

Seems like a bug, doesn't it?

Best regards  
Ronny

**Comment by pdr** [comment]
Not sure this is actually a bug. Longitude values can be -180 to 180. 8 decimal places and 10 digits only leaves room for values -99 to 99. At least I think that's how it works.

**Comment by costela** [comment]
thanks for the tip @pdr!
I have to admit this issue kinda fell through the cracks :see_no_evil: 

@GitRon can you confirm increasing the `DecimalField`'s `max_digits` helps in your case?

**Comment by GitRon** [comment]
@costela Wow, have been ages, no idea how I solved it in the end. 🙈 Sorry - but @pdr 's solution sounds legit.

**Comment by costela** [comment]
@GitRon no problem, thanks anyway for the feedback!

I'll close this issue then. It can be reopened if it pops up again.
