### ISSUE TITLE
Question: How to scrub django base user?

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#40]
Hi there!

Is there a way to define a scrubbing meta class for the base user without deriving from it and creating a new class?

Thx!

**Comment by MounirMesselmeni** [comment]
I don't think that this is possible currently. On the other hand, Django itself recommend defining an own User model when starting a new project, as the other way around will require much of work.
If you want you can propose a PR with this feature, which might be useful for third party apps too, where the model is defined there.
You can get inspired by drf spectacular on how to extend schema for a third party app
https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#blueprints

**Comment by GitRon** [comment]
Actually, I don't have a good idea on how to solve this except of extending the default user model. Maybe we should add this thought to the docs? Scrubbing the user is one of the most obvious cases, right?

**Comment by costela** [comment]
I haven't thought this through, but I maybe we could extend `SCRUBBER_GLOBAL_SCRUBBERS` to enable this.

**Comment by GitRon** [comment]
I think I have an idea. Providing a helper method which takes a model class and a scrubber class could be the solution. But avoiding code duplication will be the challenge.
