### ISSUE TITLE
Proposal: Strict mode

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#47]
Hi there!

In the last [Django Meetup Cologne](https://www.meetup.com/de-DE/Koln-Django-Meetup-Gruppe/) I talked about the django-scrubber and we were toying around with some ideas. 

I think the biggest drawback is that you have to think about scrubbing when adding new fields. 

A colleage suggested a strict mode. This would mean:
* We add a new settings variable `STRICT` which defaults to `False` for compatibility reasons
* We add a new settings variable "MODEL_FIELD_BLACKLIST" which defaults to (CharField, Textfield, etc) which have to be scrubbed
* We add a new type scrubbers.Keep to mark fields as "ok" - the scrubber will ignore those fields
* We get a warning/error during scrubbing when there one field is not defined

We could sell this as "security by design".

What do you think about this? We could get rid of the only drawback this approach has in my opinion 🙂

Best from Cologne
Ronny

**Comment by lociii** [comment]
Great to hear from you again and thanks for the well-thought proposal.

We were discussing something similar in the company lately to use for GDPR anonymization. There it also only makes sense if we force our developers to think about how a field should be treated and not let them add one without defining the handling for it.
For larger systems, this will however impose a lot of work, so doing it optional definitely makes sense.

**Comment by GitRon** [comment]
Hi @lociii 

thx for your feedback! We thought about two solutions. First, the strict mode will complain about all non-set fields (the scrubbers.Keep idea), Secondly, we thought about a "default" approach - meaning it for example will hash all undefined blacklisted field types unless you defined something more meaningful. So there is a quick fix for not exposing any data.

What do you think?

**Comment by lociii** [comment]
SGTM.
This would make it easier to get a proper start with scrubber or make it a really hardened anonymizer while still allowing for a more relaxed approach as currently offered.
@costela any thoughts from your side?

**Comment by costela** [comment]
yeah, SGTM too! :+1:

**Comment by GitRon** [comment]
How should we proceed here?

**Comment by GitRon** [comment]
Hi @costela & @lociii - what do you think about my PR? 🙂

**Comment by lociii** [comment]
Looks good. Would you mind adding documentation about the new feature? :smile:

**Comment by GitRon** [comment]
Sure, will do 👌

**Comment by GitRon** [comment]
@lociii The docs are already there but I ran a formatter so there are quite a few changes in there and the file is shown "closed" in the PR.

Fixed the pipeline - anything stopping the release now?

**Comment by GitRon** [comment]
@lociii Thx!
