### ISSUE TITLE
scrubbers.Hash failing on TextFields

### ISSUE THREAD

**Issue by meshy** [RegioHelden/django-scrubber#9]
* Django Scrubber version: 0.3.0
* Django version: any
* Python version: any
* Operating System: linux

### Description

Things go wrong when `max_length` is defined on a field as `None`.

This is the default for `TextField`s in django. I think it occurs on this line:

https://github.com/RegioHelden/django-scrubber/blob/e7f2d5c2014bd91221345bb6aeab9c8bb7e22aa7/django_scrubber/scrubbers.py#L56

### What I Did

```pytb
django.db.utils.ProgrammingError: column "none" does not exist
LINE 1: ...), "address" = SUBSTR(MD5("client"."address"), 1, None), "va...
```

We may be able to look into this next week.

**Comment by meshy** [comment]
I'll be looking into this this morning.

**Comment by costela** [comment]
Good catch! This use-case totally slipped my mind.
Should be a 1-liner + 1 test case. Or am I missing some other underlying subtlety?

**Comment by meshy** [comment]
You're right -- should be a basic one :)
